# name: CI

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/gcloud@master
#     - name: upload to app engine
#       run: cd ido-green && gcloud app deploy --project ido-green
